name: Sync from Azure DevOps

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight
  workflow_dispatch:     # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout temporary repo
        run: |
          git clone --bare https://$AZURE_USERNAME:$AZURE_PAT@dev.azure.com/$AZURE_ORG/$AZURE_PROJECT/_git/$AZURE_REPO azure-repo.git
          cd azure-repo.git
          git remote set-url origin https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_ORG/$GITHUB_REPO.git
          git push --prune --tags origin +refs/heads/*:refs/heads/*

    env:
      AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      AZURE_ORG: BoxK
      AZURE_PROJECT: BKE25
      AZURE_REPO: BKESoftware
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ORG: jacobkornn
      GITHUB_REPO: BKE
