name: Sync from Azure DevOps

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      AZURE_ORG: BoxK
      AZURE_PROJECT: BKE25
      AZURE_REPO: BKESoftware
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      GIT_ORG: jacobkornn
      GIT_REPO: BKE

    steps:
      - name: Encode Azure DevOps PAT and Clone Repo
        run: |
          echo "Encoding Azure DevOps token and cloning..."

          ENCODED_PAT=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${AZURE_PAT}'))")
          AZURE_URL="https://${AZURE_USERNAME}:${ENCODED_PAT}@dev.azure.com/${AZURE_ORG}/${AZURE_PROJECT}/_git/${AZURE_REPO}"

          echo "::add-mask::$AZURE_URL"
          git clone --bare "$AZURE_URL" azure-repo.git

      - name: Encode GitHub Token and Push Mirror
        run: |
          echo "Pushing to GitHub mirror..."

          cd azure-repo.git

          ENCODED_GIT_TOKEN=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${GIT_TOKEN}'))")
          GITHUB_URL="https://${GIT_USERNAME}:${ENCODED_GIT_TOKEN}@github.com/${GIT_ORG}/${GIT_REPO}.git"

          echo "::add-mask::$GITHUB_URL"
          git remote set-url origin "$GITHUB_URL"
          git push --mirror
